//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelIntegratedComputerSystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailRecipients
    {
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public int EmailsId { get; set; }
    
        public virtual Emails Email { get; set; }
    }
}
