//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelIntegratedComputerSystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShift
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ClockIn { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public decimal CashTakeIn { get; set; }
        public decimal CashPutInSafe { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
